### ISSUE TITLE
LND only supports bitcoind 0.18

### ISSUE THREAD

**Issue by gijswijs** [darwin/simverse#7]
The bitcoin repo uses the master branch, which is ahead of the latest release (0.18.1) Currently it's ahead in a way that makes the LND client shutdown.

This is how I fixed it for now:

```
./sv repos rm bitcoin
cd _repos
git clone --depth=1 --branch=0.18 --recursive https://github.com/bitcoin/bitcoin.git
./sv create [recipe] [name] -f
./sv enter [name]
./dc build
./dc up
```

For more info on LND only supporting 0.18, see this issue (I got the exact same error):
https://github.com/lightningnetwork/lnd/issues/3412

**Comment by darwin** [comment]
You steps to pin-point bitcoin repo are correct. You could also simply `cd _repos/bitcoin && git checkout 0.18` without cloning it again. Simverse uses whatever you have present under `_repos`.

It looks like the issue has been present for quite some time and my simverse test suite was passing regardless. So it is not triggered every time.

In general I would like to find a patch or a workaround to allow simverse to use master versions of each project. This way we find regressions early.

Can you provide some steps how to trigger this issue? I would look into it.

**Comment by gijswijs** [comment]
You can trigger it like this.

- Obviously have the latest updated repos
- Create a recipe with a LND node and a bitcoind node
- Create a simverse, enter and build,
- during `./dc up` you will see the following error from your LND node: `Unable to create chain control: unable to retrieve best block`
- Also, `./dc ps` yields an unhealthy LND node, although that might take a minute, because that might only happen after LND shuts itself down.

With regards to `git checkout`, I tried to checkout first, but git couldn't find the branch.
`git branch -r` yielded only the master branch.
Maybe because the repo was shallow? I didn't try unshallow.
