### ISSUE TITLE
What is the status of Delve integration?

### ISSUE THREAD

**Issue by gijswijs** [darwin/simverse#9]
I'm trying to get a better grip on some LND internals. So I would love to be able to add breakpoints to (preferably) multiple LND clients whilst running in a Simverse cluster.

Now, I can see that the `recipes/cookbook/templates/docker/runtime/Dockerfile` has some commented out lines that should install `dlv`, and there is a command in the toolbox to attach to the DLV port while DLV is running in headless mode inside the container.

Commenting out those line and rebuilding the cluster didn't work. (Go isn't available at that moment to be able to install Delve) But with some manual commands I was able to get Delve to run, and to run the dlv_attach command.

But my breakpoints aren't hit and I am not sure why.

So my question is twofold:
1) What is the status of DLV for the LND and BTCD containers? How am I supposed to use it.
2) How do you map the source files on the host to the source files on the container (e.g. for LND) so that you can set breakpoints properly? (Or more generally: How do you set breakpoints?)

Bonus question:
Do you have ideas on debugging for c-lightning and eclair as well?

Thanks for any feedback and pointers you can give me. If you want help on this repo, just let me know. It's been a huge timesaver for me, so it is the least I can do.

**Comment by darwin** [comment]
I don't remember exactly but at some point early in the development of simverse I had dvelve working with IntelliJ GoLand IDE. I was able to hit a breakpoint and step go code from host machine (macOS). But the code had to be compiled with no optimizations. Not sure if file mapping was an issue.

Later I restructured simverse a lot and didn't spend time to keep dlv working.  That would also raise question how to support C or Scala debugging for other projects. I'm sorry I have no useful insights here.

**Comment by darwin** [comment]
If you want to develop something specific I would personally try to use simverse in "hybrid" mode. I would run the code you want to develop directly on the host machine and connect it with rest of the cluster inside simverse. That should avoid a lot of debugger interop problems.

https://github.com/darwin/simverse#what-is-the-difference-between-heterogeneous-and-hybrid-simnets

**Comment by gijswijs** [comment]
Took your advice and used Simverse in hybrid mode. I wrote a post about how my setup now works. https://gijswijs.github.io/posts/debugging-lnd/

**Comment by darwin** [comment]
Nice work. I would link to your article from the simverse readme.
